---
version: 2
project_name: fireactions

builds:
- id: fireactions
  main: ./cmd/fireactions
  env:
  - CGO_ENABLED=0
  binary: fireactions
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ldflags:
  - -X github.com/ALameLlama/fireactions.Version={{ .Version }}
  - -X github.com/ALameLlama/fireactions.Commit={{ .ShortCommit }}
  - -X github.com/ALameLlama/fireactions.Date={{ .CommitDate }}

archives:
- id: fireactions
  ids:
  - fireactions
  name_template: fireactions-v{{ .Version }}-{{ .Os }}-{{ .Arch }}
  formats:
  - tar.gz

dockers_v2:
- id: fireactions
  ids:
  - fireactions
  dockerfile: Dockerfile
  images:
  - ghcr.io/alamellama/fireactions
  tags:
  - "{{ .Version }}"
  - latest
  platforms:
  - linux/amd64
  - linux/arm64
  extra_files:
  - entrypoint.sh
  flags:
  - "--pull=true"
- id: fireactions-amd64
  ids:
  - fireactions
  dockerfile: Dockerfile
  images:
  - ghcr.io/alamellama/fireactions
  tags:
  - "{{ .Version }}-amd64"
  platforms:
  - linux/amd64
  extra_files:
  - entrypoint.sh
  flags:
  - "--pull=true"
- id: fireactions-arm64
  ids:
  - fireactions
  dockerfile: Dockerfile
  images:
  - ghcr.io/alamellama/fireactions
  tags:
  - "{{ .Version }}-arm64"
  platforms:
  - linux/arm64
  extra_files:
  - entrypoint.sh
  flags:
  - "--pull=true"

# Changelog is managed by release-please
changelog:
  disable: true

checksum:
  name_template: fireactions-v{{ .Version }}-checksums.txt
